'use strict';
const $ = id => document.getElementById(id);
const SESSION_KEY='tf_session_v1';
let session=null;
try{session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');}catch{}
if(!session?.email)location.replace('index.html');
const USER_EMAIL=(session?.email||'local-demo').toLowerCase();
const KEY=`tf_tasks_v1::${USER_EMAIL}`;
const LEGACY_KEY='tf_tasks_v1';
const LEGACY_MIGRATION_KEY='tf_legacy_tasks_claimed_v1';
const statuses = {ToDo:'To do',InProgress:'In progress',Done:'Completed'};
const paths = {grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',sun:'M12 3V1 M12 23v-2 M3 12H1 M23 12h-2 M4 4l2 2 M18 18l2 2 M4 20l2-2 M18 6l2-2 M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',calendar:'M5 3v4 M19 3v4 M3 10h18 M5 5h14a2 2 0 0 1 2 2v13H3V7a2 2 0 0 1 2-2 M7 14h3 M14 14h3',check:'M5 12l4 4L19 6',download:'M12 3v12 M7 10l5 5 5-5 M4 16v5h16v-5',moon:'M20 15A9 9 0 0 1 9 4 9 9 0 1 0 20 15',plus:'M12 5v14 M5 12h14',layers:'m12 3 10 5-10 5L2 8z M2 12l10 5 10-5 M2 16l10 5 10-5',activity:'M2 12h5l3-8 4 16 3-8h5',clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M12 6v6l4 2',columns:'M3 4h18v16H3z M9 4v16 M15 4v16',list:'M8 6h13 M8 12h13 M8 18h13 M3 6h.1 M3 12h.1 M3 18h.1',search:'M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0 M15 15l6 6',trash:'M3 6h18 M9 6V3h6v3 M5 6l1 15h12l1-15 M10 10v7 M14 10v7',x:'M6 6l12 12 M6 18 18 6',edit:'m15 4 5 5 M4 15 16 3a2 2 0 0 1 5 5L9 20l-6 1z'};
function icon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.plus}"/></svg>`;}
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
const escapeHTML = str => String(str??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let tasks=[],scope='All',view='board',toastTimer,undoAction=null,storageError=false;
try{
 let raw=localStorage.getItem(KEY);
 if(raw===null){const legacy=localStorage.getItem(LEGACY_KEY),claimed=localStorage.getItem(LEGACY_MIGRATION_KEY);if(legacy&&!claimed){raw=legacy;localStorage.setItem(KEY,legacy);localStorage.setItem(LEGACY_MIGRATION_KEY,USER_EMAIL);}}
 const saved=JSON.parse(raw||'[]');if(!Array.isArray(saved))throw Error('Invalid tasks');
 tasks=saved.filter(t=>t&&typeof t.id==='string'&&typeof t.title==='string').map(t=>({...t,status:statuses[t.status]?t.status:'ToDo',priority:['High','Medium','Low'].includes(t.priority)?t.priority:'Medium',description:String(t.description||''),due_date:/^\d{4}-\d{2}-\d{2}$/.test(t.due_date||'')?t.due_date:'',created_at:String(t.created_at||'')}));
}catch{storageError=true;}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function overdue(t){return Boolean(t.due_date&&t.due_date<today()&&t.status!=='Done');}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(tasks));storageError=false;$('saveStatus').textContent='Saved for this account on this browser';$('saveStatus').classList.remove('storage-error');}catch{storageError=true;$('saveStatus').textContent='Not saved — export a backup';$('saveStatus').classList.add('storage-error');}render();}
function toast(message,undo=null){clearTimeout(toastTimer);undoAction=undo;$('toastText').textContent=storageError?`${message} Changes are not saved; export a backup.`:message;$('undoBtn').hidden=!undo;$('toast').classList.add('visible');toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),undo?10000:4500);}
$('undoBtn').onclick=()=>{if(undoAction){undoAction();undoAction=null;persist();toast('Change undone.');}};
function visibleTasks(){const q=$('searchInput').value.trim().toLowerCase();const priority=$('filterPriority').value;let list=tasks.filter(t=>(!q||(t.title+' '+t.description).toLowerCase().includes(q))&&(priority==='All'||t.priority===priority)&&(scope==='All'||(scope==='Today'&&t.due_date===today()&&t.status!=='Done')||(scope==='Upcoming'&&t.due_date>today()&&t.status!=='Done')||(scope==='Done'&&t.status==='Done')));const sort=$('sortBy').value;const score={High:3,Medium:2,Low:1};return list.sort((a,b)=>{if(sort==='created_asc')return a.created_at.localeCompare(b.created_at);if(sort==='due_asc')return(a.due_date||'9999').localeCompare(b.due_date||'9999');if(sort==='due_desc')return(b.due_date||'0000').localeCompare(a.due_date||'0000');if(sort==='priority_desc')return score[b.priority]-score[a.priority];if(sort==='priority_asc')return score[a.priority]-score[b.priority];return b.created_at.localeCompare(a.created_at);});}
function card(t,index){const due=t.due_date?new Date(t.due_date+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',...(t.due_date.slice(0,4)!==today().slice(0,4)?{year:'numeric'}:{})}):'No due date';return `<article class="task-card" data-id="${escapeHTML(t.id)}" style="animation-delay:${Math.min(index*40,240)}ms"><div class="task-top"><span class="priority ${t.priority}">${t.priority} priority</span><div class="card-actions"><button data-action="edit" aria-label="Edit ${escapeHTML(t.title)}" title="Edit task">${icon('edit')}</button><button data-action="delete" aria-label="Delete ${escapeHTML(t.title)}" title="Delete task">${icon('trash')}</button></div></div><div class="task-content"><h3>${escapeHTML(t.title)}</h3><p>${escapeHTML(t.description||'Add a description to make your next step clearer.')}</p></div><div class="card-footer"><span class="due ${overdue(t)?'overdue':''}">${icon('calendar')}${escapeHTML(due)}${overdue(t)?' · Overdue':''}</span><button class="complete-button" data-action="toggle" aria-label="${t.status==='Done'?'Reopen':'Complete'} ${escapeHTML(t.title)}" title="${t.status==='Done'?'Reopen task':'Mark completed'}" aria-pressed="${t.status==='Done'}">${icon('check')}</button></div></article>`;}
function render(){const done=tasks.filter(t=>t.status==='Done').length;const stats={statTotal:tasks.length,statProgress:tasks.filter(t=>t.status==='InProgress').length,statDone:done,statOverdue:tasks.filter(overdue).length,navTotal:tasks.length,navToday:tasks.filter(t=>t.due_date===today()&&t.status!=='Done').length};Object.entries(stats).forEach(([id,val])=>{const el=$(id);if(el.textContent!==String(val)){el.textContent=val;if(!matchMedia('(prefers-reduced-motion: reduce)').matches)el.animate([{opacity:.4,transform:'translateY(4px)'},{opacity:1,transform:'translateY(0)'}],{duration:300});}});const percent=tasks.length?Math.round(done/tasks.length*100):0;$('progressRing').style.setProperty('--progress',percent+'%');$('progressPercent').textContent=percent+'%';$('progressCopy').textContent=tasks.length?`${done} of ${tasks.length} tasks completed`:'Your next chapter starts here.';$('clearAllBtn').disabled=!tasks.length;$('exportBtn').disabled=!tasks.length;$('demoBtn').hidden=tasks.length>0;
const list=visibleTasks();$('visibleCount').textContent=list.length;$('taskList').className=view==='board'?'board':'board list-view';$('taskList').innerHTML=Object.entries(statuses).filter(([key])=>scope!=='Done'||key==='Done').map(([key,label])=>{const group=list.filter(t=>t.status===key);return `<section class="column ${key}" aria-label="${label}"><div class="column-header"><span class="status-dot"></span>${label}<span class="column-count">${group.length}</span><button class="column-add" data-add-status="${key}" aria-label="Add ${label.toLowerCase()} task">${icon('plus')}</button></div><div class="cards">${group.length?group.map(card).join(''):`<div class="empty-column"><span>${key==='Done'?'✓':key==='InProgress'?'↗':'＋'}</span>${list.length||tasks.length?'No matching tasks here.':key==='ToDo'?'A clear space for your next idea.':key==='InProgress'?'Your next step starts here.':'Your wins will live here.'}</div>`}</div><button class="add-in-column" data-add-status="${key}">${icon('plus')} Add task</button></section>`;}).join('');}
function openTask(task=null,status='ToDo'){ $('taskForm').reset();$('editId').value=task?.id||'';$('title').value=task?.title||'';$('description').value=task?.description||'';$('dueDate').value=task?.due_date||'';$('priority').value=task?.priority||'Medium';$('status').value=task?.status||status;$('dialogTitle').textContent=task?'Edit task':'Create a task';$('submitBtn').textContent=task?'Save changes':'Create task';$('taskDialog').showModal();$('title').focus();}
function celebrate(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<22;i++){const piece=document.createElement('i');piece.className='confetti';piece.style.cssText=`--x:${(Math.random()-.5)*500}px;--y:${(Math.random()-.5)*380}px;--r:${Math.random()*720}deg;--color:${['#74a787','#d4b875','#a8beca','#b6caaa'][i%4]}`;$('celebration').append(piece);setTimeout(()=>piece.remove(),900);}}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add],[data-add-status]');if(add)openTask(null,add.dataset.addStatus||'ToDo');const nav=e.target.closest('[data-scope]');if(nav){scope=nav.dataset.scope;document.querySelectorAll('[data-scope]').forEach(b=>{b.classList.toggle('active',b===nav);if(b===nav)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});$('tasksHeading').textContent={All:'All tasks',Today:'Due today',Upcoming:'Upcoming tasks',Done:'Completed tasks'}[scope];render();}});
$('taskList').addEventListener('click',e=>{const button=e.target.closest('[data-action]');if(!button)return;const task=tasks.find(t=>t.id===button.closest('[data-id]').dataset.id);if(!task)return;if(button.dataset.action==='edit')return openTask(task);if(button.dataset.action==='delete'){const index=tasks.indexOf(task);tasks.splice(index,1);persist();toast('Task deleted.',()=>tasks.splice(Math.min(index,tasks.length),0,task));}else{const previous=task.status;task.status=previous==='Done'?'ToDo':'Done';task.updated_at=new Date().toISOString();persist();if(task.status==='Done')celebrate();toast(task.status==='Done'?'One more done. Nice work.':'Task reopened.',()=>{const current=tasks.find(t=>t.id===task.id);if(current)current.status=previous;});}});
$('taskForm').onsubmit=e=>{e.preventDefault();const title=$('title').value.trim();if(!title){$('title').setCustomValidity('Enter a task title.');$('title').reportValidity();return;}const id=$('editId').value;const patch={title,description:$('description').value.trim(),due_date:$('dueDate').value,priority:$('priority').value,status:$('status').value,updated_at:new Date().toISOString()};if(id){const task=tasks.find(t=>t.id===id);if(task)Object.assign(task,patch);}else{tasks.push({...patch,id:'t_'+Date.now()+'_'+Math.random().toString(16).slice(2),created_at:new Date().toISOString()});}persist();$('taskDialog').close();toast(id?'Task updated.':'Task created. Make it happen.');};
$('title').oninput=()=>$('title').setCustomValidity('');$('closeModalBtn').onclick=$('cancelBtn').onclick=()=>$('taskDialog').close();
for(const id of ['taskDialog','confirmDialog'])$(id).addEventListener('click',e=>{if(e.target===$(id)){const r=$(id).getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$(id).close();}});
$('clearAllBtn').onclick=()=>$('confirmDialog').showModal();$('cancelClear').onclick=()=>$('confirmDialog').close();$('confirmClear').onclick=()=>{const previous=tasks;tasks=[];persist();$('confirmDialog').close();toast('Workspace cleared.',()=>{tasks=[...previous,...tasks];});};
$('searchInput').oninput=render;$('filterPriority').onchange=$('sortBy').onchange=render;
function setView(value){view=value;['board','list'].forEach(v=>{$(v+'Btn').classList.toggle('selected',v===value);$(v+'Btn').setAttribute('aria-pressed',String(v===value));});render();}
$('boardBtn').onclick=()=>setView('board');$('listBtn').onclick=()=>setView('list');
const THEME_KEY='tf_theme';
const themeMedia=matchMedia('(prefers-color-scheme: dark)');
function currentTheme(){return document.documentElement.classList.contains('dark')?'dark':'light';}
function syncThemeControls(){
 const dark=currentTheme()==='dark',next=dark?'light':'dark';
 $('themeLabel').textContent=dark?'Light appearance':'Dark appearance';
 for(const id of ['themeBtn','mobileTheme']){
  const btn=$(id);if(!btn)continue;
  btn.setAttribute('aria-pressed',String(dark));
  btn.setAttribute('aria-label',`Switch to ${next} appearance`);
  btn.title=`Switch to ${next} appearance`;
  const holder=btn.querySelector('[data-icon]');if(holder)holder.innerHTML=icon(dark?'sun':'moon');
 }
 const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=dark?'#1f2d25':'#184d3e';
}
function applyTheme(theme,{remember=true}={}){
 const dark=theme==='dark';
 document.documentElement.classList.toggle('dark',dark);
 document.body.classList.remove('dark');
 if(remember){try{localStorage.setItem(THEME_KEY,theme);}catch{}}
 syncThemeControls();
}
function toggleTheme(){applyTheme(currentTheme()==='dark'?'light':'dark');}
$('themeBtn').onclick=toggleTheme;
themeMedia.addEventListener?.('change',e=>{try{if(!localStorage.getItem(THEME_KEY))applyTheme(e.matches?'dark':'light',{remember:false});}catch{}});
$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(tasks,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`taskflow-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Task backup exported.');};
$('focusBtn').onclick=()=>{const pending=tasks.filter(t=>t.status!=='Done').sort((a,b)=>(a.due_date||'9999').localeCompare(b.due_date||'9999')||({High:3,Medium:2,Low:1}[b.priority]-{High:3,Medium:2,Low:1}[a.priority]));if(!pending.length){openTask();return;}document.querySelector('[data-scope="All"]').click();$('searchInput').value='';$('filterPriority').value='All';render();const target=[...document.querySelectorAll('[data-id]')].find(el=>el.dataset.id===pending[0].id);target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});target.classList.add('spotlight');target.querySelector('[data-action="edit"]').focus({preventScroll:true});toast('Start here: your next due task.');};
$('demoBtn').onclick=()=>{if(tasks.length)return;const date=new Date();const offset=n=>{const d=new Date(date.getFullYear(),date.getMonth(),date.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};const examples=[['Plan the week ahead','Set three priorities and make space for focused work.','High','ToDo',1],['Collect a little inspiration','Save ideas, references, and things worth coming back to.','Low','ToDo',3],['Bring your next idea to life','Break the big picture into small, achievable steps.','High','InProgress',0],['Refresh your portfolio','Add your latest work and tell the story behind it.','Medium','InProgress',2],['Set up your workspace','A clear workspace. A fresh start. You’re ready to go.','Low','Done',0],['Map out the first milestone','Define what done looks like before getting started.','Medium','Done',-1]];tasks=examples.map(([title,description,priority,status,n],i)=>({id:'demo_'+Date.now()+'_'+i,title,description,priority,status,due_date:offset(n),created_at:new Date(Date.now()-i*1000).toISOString(),updated_at:new Date().toISOString()}));persist();toast('Sample tasks added. Edit them to make them yours.');};
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.target.closest('input,textarea,select,[contenteditable="true"]')||document.querySelector('dialog[open]'))return;if(e.key.toLowerCase()==='n'){e.preventDefault();openTask();}if(e.key==='/'){e.preventDefault();$('searchInput').focus();}});
window.addEventListener('storage',e=>{if(e.key===KEY)toast('Tasks changed in another tab. Reload to see the latest version.');});
const userName=String(session?.name||'My workspace').trim();
const initials=userName.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase()||'ME';
if($('profileName'))$('profileName').textContent=userName;
if($('profileEmail'))$('profileEmail').textContent=USER_EMAIL;
if($('workspaceName'))$('workspaceName').textContent=`${userName.split(/\s+/)[0]||'Personal'} workspace`;
for(const id of ['profileInitials','topInitials'])if($(id))$(id).textContent=initials;
function logout(){try{localStorage.removeItem(SESSION_KEY);}catch{}location.href='index.html';}
$('logoutBtn')?.addEventListener('click',logout);$('mobileLogout')?.addEventListener('click',logout);
$('dateLabel').textContent=new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'}).toUpperCase();syncThemeControls();render();if(storageError){$('saveStatus').textContent='Storage unavailable or unreadable';$('saveStatus').classList.add('storage-error');toast('Could not read saved tasks. Export any visible tasks before leaving.');}
$('mobileTheme').onclick=toggleTheme;$('mobileExport').onclick=()=>{if(tasks.length)$('exportBtn').click();else toast('Add a task before exporting.');};
